mod route_get_licenses;
mod route_create_license;
mod route_access_server;
mod route_delete_from_id;
mod route_delete_from_token;
mod route_email_exists;
mod route_get;
mod route_has_access;
mod route_organizations;
mod route_register;
mod route_renew;
mod route_server_authenticate;
mod route_server_disconnect;
mod route_update;
mod route_update_auth;
mod route_from_email;
mod route_check_license;
mod route_add_perm;

pub use route_get_licenses::*;
pub use route_create_license::*;
pub use route_access_server::*;
pub use route_delete_from_id::*;
pub use route_delete_from_token::*;
pub use route_email_exists::*;
pub use route_get::*;
pub use route_has_access::*;
pub use route_organizations::*;
pub use route_register::*;
pub use route_renew::*;
pub use route_server_authenticate::*;
pub use route_server_disconnect::*;
pub use route_update::*;
pub use route_update_auth::*;
pub use route_from_email::*;
pub use route_check_license::*;
pub use route_add_perm::*;
