- name: API Compilation
  hosts: uverworld-website
  remote_user: root

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Switch to Rust nightly
      shell: ~/.cargo/bin/rustup default nightly
      tags:
        - rust

    - name: Install build essentials
      ansible.builtin.apt:
        name: build-essential
        state: present
      become: yes

    - name: Install required packages for Rust compilation
      ansible.builtin.apt:
        name:
          - pkg-config
          - libssl-dev
          - libudev-dev
        state: present
      become: yes

    - name: Build the binary
      ansible.builtin.shell:
        cmd: ~/.cargo/bin/cargo +nightly build --release
        executable: /bin/bash
        chdir: "~/api/server"

