name: Rust Test of the API's crate

on:
  push:
    branches:
      - master
    paths:
      - 'server/crates/api/**'
  pull_request:
    branches:
      - master
    paths:
      - 'server/crates/api/**'

jobs:
  docker_test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        env:
          DOCKER_DRIVER: overlay
          DOCKER_HOST: tcp://localhost:2375

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustc, cargo

    - name: Setup Docker
      run: |
        sudo service docker start

    - name: Build and test
      run: |
        cd server/crates/api && cargo test
