name: Rust Clippy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust nightly # ATM, the feature "let_chains" is unstable, so we have to use nightly for our testing and release.
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy

    - name: Run cargo clippy
      run: |
        cd server
        cargo +nightly clippy
