name: Rust Clippy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clippy_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Run cargo clippy
      run: |
        cd server
        cargo clippy
