name: coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Docker service
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          service docker start

      - name: Generate code coverage
        run: |
          cd server
          cargo +nightly tarpaulin --verbose --all --all-features --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
